import { CategoryId, Movie } from "@/types/movie";

let uid = 1;
const m = (category: CategoryId, title: string, year: number, rating: number, tagline: string): Movie =>
  ({ id: uid++, category, title, year, rating, tagline });

export const MOVIES: Movie[] = [
  // 🎬 Hollywood
  m("hollywood", "The Godfather", 1972, 8.7, "An offer you can't refuse."),
  m("hollywood", "The Shawshank Redemption", 1994, 8.7, "Hope keeps you alive."),
  m("hollywood", "The Dark Knight", 2008, 8.5, "Why so serious?"),
  m("hollywood", "Pulp Fiction", 1994, 8.5, "Crime, wit and chaos."),
  m("hollywood", "Forrest Gump", 1994, 8.5, "Life is a box of chocolates."),
  m("hollywood", "Goodfellas", 1990, 8.7, "As far back as I remember..."),
  m("hollywood", "Schindler's List", 1993, 8.6, "Whoever saves one life..."),
  m("hollywood", "The Silence of the Lambs", 1991, 8.3, "Evil has a voice."),
  m("hollywood", "Whiplash", 2014, 8.4, "Not quite my tempo."),
  m("hollywood", "The Social Network", 2010, 7.7, "500 million friends, few enemies."),
  m("hollywood", "Citizen Kane", 1941, 8.3, "Rosebud."),
  m("hollywood", "La La Land", 2016, 8.0, "A tribute to dreamers."),
  // 🪔 Bollywood
  m("bollywood", "3 Idiots", 2009, 8.1, "Aal izz well."),
  m("bollywood", "Dangal", 2016, 7.9, "Mhari chhoriyan chhoron se kam hain?"),
  m("bollywood", "Taare Zameen Par", 2007, 8.3, "Every child is special."),
  m("bollywood", "Andhadhun", 2018, 8.2, "What a life!"),
  m("bollywood", "Queen", 2014, 8.1, "Her own honeymoon."),
  m("bollywood", "Zindagi Na Milegi Dobara", 2011, 7.9, "Live once, truly."),
  m("bollywood", "Dilwale Dulhania Le Jayenge", 1995, 8.0, "Raj aur Simran, forever."),
  m("bollywood", "Swades", 2004, 8.1, "Home is where the heart is."),
  m("bollywood", "Sholay", 1975, 8.1, "Kitne aadmi the?"),
  m("bollywood", "Mughal-E-Azam", 1960, 8.0, "Love that defied an empire."),
  m("bollywood", "Barfi!", 2012, 8.1, "Happiness, in silence."),
  m("bollywood", "Gully Boy", 2019, 7.9, "Apna time aayega."),
  // 🍿 Blockbusters
  m("blockbusters", "Avengers: Endgame", 2019, 8.4, "Whatever it takes."),
  m("blockbusters", "Avatar", 2009, 7.6, "A new world awaits."),
  m("blockbusters", "Titanic", 1997, 7.9, "Never let go."),
  m("blockbusters", "Jurassic Park", 1993, 7.9, "Life finds a way."),
  m("blockbusters", "Star Wars: A New Hope", 1977, 8.6, "A long time ago..."),
  m("blockbusters", "Inception", 2010, 8.4, "Your mind is the crime scene."),
  m("blockbusters", "Interstellar", 2014, 8.4, "Love transcends dimensions."),
  m("blockbusters", "The Matrix", 1999, 8.2, "There is no spoon."),
  m("blockbusters", "Gladiator", 2000, 8.5, "Strength and honor."),
  m("blockbusters", "The Lord of the Rings: The Fellowship of the Ring", 2001, 8.4, "One ring to rule them all."),
  m("blockbusters", "Top Gun: Maverick", 2022, 8.2, "Feel the need."),
  m("blockbusters", "Spider-Man: Into the Spider-Verse", 2018, 8.4, "Anyone can wear the mask."),
  // 🏛️ Classics
  m("classics", "12 Angry Men", 1957, 8.5, "Justice is a jury."),
  m("classics", "Casablanca", 1942, 8.4, "Here's looking at you, kid."),
  m("classics", "Psycho", 1960, 8.5, "A boy's best friend is his mother."),
  m("classics", "Rear Window", 1954, 8.4, "Watch closely."),
  m("classics", "Singin' in the Rain", 1952, 8.3, "Pure movie joy."),
  m("classics", "It's a Wonderful Life", 1946, 8.3, "No man is a failure with friends."),
  m("classics", "The Good, the Bad and the Ugly", 1966, 8.5, "The way you walk..."),
  m("classics", "Lawrence of Arabia", 1962, 8.3, "The desert is everything."),
  m("classics", "Roman Holiday", 1953, 8.0, "Rome, by any other name."),
  m("classics", "Gone with the Wind", 1939, 7.9, "Frankly, my dear..."),
  m("classics", "To Kill a Mockingbird", 1962, 8.2, "Courage has no color."),
  m("classics", "On the Waterfront", 1954, 8.1, "I coulda been a contender."),
  // 🌍 International
  m("international", "Parasite", 2019, 8.5, "Act like you own it."),
  m("international", "Spirited Away", 2001, 8.6, "The tunnel led somewhere strange."),
  m("international", "Life Is Beautiful", 1997, 8.4, "Love wins, even here."),
  m("international", "City of God", 2002, 8.4, "Fight and you'll never survive."),
  m("international", "Pan's Labyrinth", 2006, 8.2, "Innocence has a monster."),
  m("international", "The Intouchables", 2011, 8.5, "Friendship beyond limits."),
  m("international", "Cinema Paradiso", 1988, 8.5, "A love letter to cinema."),
  m("international", "Seven Samurai", 1954, 8.6, "The farmers won; the samurai lost."),
  m("international", "Crouching Tiger, Hidden Dragon", 2000, 7.9, "Grace is a blade."),
  m("international", "The Handmaiden", 2016, 8.1, "Deception, beautifully told."),
  m("international", "Train to Busan", 2016, 7.6, "Next stop: survival."),
  m("international", "The Lives of Others", 2006, 8.4, "Listening changes everything."),
  // 💎 Hidden Gems
  m("hidden-gems", "The Fall", 2006, 7.8, "A story worth dying for."),
  m("hidden-gems", "Coherence", 2013, 7.2, "One night, two realities."),
  m("hidden-gems", "The Man from Earth", 2007, 7.9, "14,000 years of stories."),
  m("hidden-gems", "Primer", 2004, 6.9, "Trust no one, especially yourself."),
  m("hidden-gems", "Hunt for the Wilderpeople", 2016, 7.8, "A majestic adventure, eh."),
  m("hidden-gems", "The Peanut Butter Falcon", 2019, 7.6, "A modern Mark Twain tale."),
  m("hidden-gems", "Leave No Trace", 2018, 7.1, "Quietly unforgettable."),
  m("hidden-gems", "The Red Turtle", 2016, 7.5, "Survival, wordlessly beautiful."),
  m("hidden-gems", "Song of the Sea", 2014, 8.0, "A selkie's song."),
  m("hidden-gems", "Embrace of the Serpent", 2015, 7.9, "The jungle remembers."),
  m("hidden-gems", "Moon", 2009, 7.8, "The last place you'd look: yourself."),
  m("hidden-gems", "I Origins", 2014, 7.3, "Eyes don't lie."),
  // 🛋️ Family Night
  m("family", "Toy Story", 1995, 8.0, "To infinity and beyond!"),
  m("family", "The Lion King", 1994, 8.3, "Hakuna matata, always."),
  m("family", "Finding Nemo", 2003, 7.8, "Just keep swimming."),
  m("family", "Up", 2009, 7.9, "Adventure is out there."),
  m("family", "Inside Out", 2015, 8.1, "Feelings run the show."),
  m("family", "Coco", 2017, 8.4, "Remember me."),
  m("family", "Shrek", 2001, 7.7, "Ogres are like onions."),
  m("family", "How to Train Your Dragon", 2010, 7.8, "Befriend the storm."),
  m("family", "Paddington 2", 2017, 7.8, "If you're kind and polite..."),
  m("family", "Ratatouille", 2007, 7.7, "Anyone can cook."),
  m("family", "The Incredibles", 2004, 7.7, "No capes!"),
  m("family", "Home Alone", 1990, 7.7, "A man's home is his castle."),
  // 🎥 Documentaries
  m("documentaries", "Free Solo", 2018, 8.1, "No rope, no fear, no equal."),
  m("documentaries", "Senna", 2010, 8.5, "No fear. No limits."),
  m("documentaries", "Man on Wire", 2008, 7.7, "A crime of poetry."),
  m("documentaries", "Amy", 2015, 7.8, "The girl behind the voice."),
  m("documentaries", "Blackfish", 2013, 8.1, "A killer whale's truth."),
  m("documentaries", "The Cove", 2009, 8.4, "Expose the unspeakable."),
  m("documentaries", "My Octopus Teacher", 2020, 7.9, "An unlikely friendship."),
  m("documentaries", "13th", 2016, 8.2, "The prison of history."),
  m("documentaries", "Searching for Sugar Man", 2012, 8.2, "Too good to be true."),
  m("documentaries", "Won't You Be My Neighbor?", 2018, 8.4, "Radical kindness."),
  m("documentaries", "The Act of Killing", 2012, 8.2, "History, reenacted by its villains."),
  m("documentaries", "March of the Penguins", 2005, 7.5, "Love, ice and endurance."),
  // 🌤️ Feel Good
  m("feel-good", "The Grand Budapest Hotel", 2014, 8.1, "A perfectly pink caper."),
  m("feel-good", "Little Miss Sunshine", 2006, 7.8, "Winning is overrated."),
  m("feel-good", "The Pursuit of Happyness", 2006, 8.0, "Protect your dream."),
  m("feel-good", "Good Will Hunting", 1997, 8.3, "It's not your fault."),
  m("feel-good", "The Truman Show", 1998, 8.2, "In case I don't see you..."),
  m("feel-good", "About Time", 2013, 7.8, "Live every day twice, kindly."),
  m("feel-good", "Midnight in Paris", 2011, 7.7, "Nostalgia is a time machine."),
  m("feel-good", "Chef", 2014, 7.3, "A food truck full of heart."),
  m("feel-good", "The Hundred-Foot Journey", 2014, 7.3, "Flavors that unite."),
  m("feel-good", "500 Days of Summer", 2009, 7.7, "A story about love, not a love story."),
  m("feel-good", "The Devil Wears Prada", 2006, 6.9, "That's all."),
  m("feel-good", "Julie & Julia", 2009, 7.0, "Butter, blogs and joy."),
  // 👁️ Cult Favorites
  m("cult", "The Big Lebowski", 1998, 8.1, "The Dude abides."),
  m("cult", "Fight Club", 1999, 8.4, "First rule: no spoilers."),
  m("cult", "Donnie Darko", 2001, 8.0, "28 days, 6 hours, 42 minutes."),
  m("cult", "Blade Runner", 1982, 8.1, "Tears in rain."),
  m("cult", "A Clockwork Orange", 1971, 8.3, "A bit of the old ultraviolence."),
  m("cult", "The Rocky Horror Picture Show", 1975, 7.4, "Don't dream it, be it."),
  m("cult", "Night of the Living Dead", 1968, 7.8, "They're coming to get you."),
  m("cult", "Brazil", 1985, 7.9, "Bureaucracy, dreams and ducts."),
  m("cult", "They Live", 1988, 7.2, "Obey. Consume. Wake up."),
  m("cult", "Eraserhead", 1977, 7.3, "Industrial dreams, unsettling."),
  m("cult", "Army of Darkness", 1992, 7.4, "Hail to the king, baby."),
  m("cult", "The Room", 2003, 3.7, "Oh hi, Mark."),
];

export const moviesByCategory = (id: CategoryId): Movie[] =>
  MOVIES.filter((mv) => mv.category === id);
